name: flutter_engineer_challenge
description: Flutter Engineer Challenge.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluro: ^1.5.1
  flutter_launcher_icons: ^0.7.4
  provider: ^3.0.0
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/flutter-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/flutter-logo.png
    - assets/avatar.jpeg
    - assets/data/friends.json
    - assets/data/me.json

  fonts:
    - family: GothamRounded
      fonts:
        - asset: assets/fonts/GothamRounded-Medium.ttf
          weight: 500